(in-package :cl-minion)

(defun parse (json-string)
  (list :json (val (make-string-input-stream json-string))))

(defun val (s)
  (case (peek-char t s nil nil)
    (#\{ (obj s))
    (#\[ (arr s))
    (#\" (key s))
    (#\t (id s "true" '(true)))
    (#\f (id s "false" '(false)))
    (#\n (id s "null" '(null)))
    (otherwise nil)))

(defun arr (s)
  (list :array
        (append (w/o-wp s (match #\[ s))
                (val s)
                (loop for rep = (match-if #\, s)
                      :while (and rep (char= rep #\,) (read-char s nil))
                      :append (val s))
                (w/o-wp s (match #\] s)))))

(defun obj (s)
  (list :object (append (w/o-wp s (match #\{ s))
                        (w/o-wp s (pairs s))
                        (w/o-wp s (match #\} s)))))

(defun pairs (s)
  (list (pair s)
        (loop for rep = (match-if #\, s)
              :while (and rep (char= rep #\,) (read-char s nil))
              :append (pair s))))

(defun pair (s)
  (list ':pair (append (w/o-wp s (key s))
                       (w/o-wp s (match #\: s))
                       (w/o-wp s (val s)))))

(defun key (s)
  (match #\" s)
  (list ':key (loop for char = (read-char s nil)
                    while (char/= char #\")
                    collect char)))

(defun id (s string value)
  (loop for e in (coerce string 'list)
        for n = (read-char s nil)
        :unless (char= e n) :do (error "Unrecognized keyword!")
        :finally (return value)))
